// 供应商预设：地址/默认模型/协议均为各厂商公开的 OpenAI 兼容接口（或 Anthropic 原生接口）
// 接口地址会变，填错了改「接口地址」输入框即可，不影响其它功能。

export type Protocol = 'openai' | 'anthropic' | 'ollama';

// 同一供应商的不同计费方案 / 接入点：地址与 Key 格式都可能不同（如小米 MiMo 的按量付费 sk- 与 Token Plan tp-）
export interface ProviderPlan {
  name: string;
  baseUrl: string;
  keyFormat?: string; // 该方案的 Key 格式（用于输入框提示）
  keyTest?: RegExp; // 软校验：不匹配只提示，不拦截（用户可能用中转 Key）
}

export interface ProviderPreset {
  id: string;
  name: string;
  group: '国内云' | '海外' | '聚合/中转' | '本地';
  baseUrl: string;
  model: string; // 默认模型；留空表示需点「获取模型列表」选择
  models?: string[]; // 常用模型快捷选择
  protocol: Protocol;
  needKey: boolean;
  keyUrl?: string; // 申请 Key 的控制台地址
  keyFormat?: string; // Key 格式提示（默认视为 sk- 开头）
  keyTest?: RegExp; // Key 软校验
  plans?: ProviderPlan[]; // 订阅制 / 多接入点的厂商提供切换
  note?: string; // 使用注意（鉴权格式、模型名规则等）
}

export const PROVIDERS: ProviderPreset[] = [
  // ---------- 国内云 ----------
  {
    id: 'deepseek',
    name: 'DeepSeek',
    group: '国内云',
    baseUrl: 'https://api.deepseek.com/v1',
    model: 'deepseek-chat',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://platform.deepseek.com/api_keys',
    keyFormat: 'sk-…',
    keyTest: /^sk-/,
  },
  {
    id: 'qwen',
    name: '通义千问（阿里云百炼）',
    group: '国内云',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    model: 'qwen-plus',
    models: ['qwen-plus', 'qwen-turbo', 'qwen-max', 'qwen-long'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://bailian.console.aliyun.com/?tab=model#/api-key',
    keyFormat: 'sk-…',
    keyTest: /^sk-/,
  },
  {
    id: 'kimi',
    name: 'Kimi（月之暗面）',
    group: '国内云',
    baseUrl: 'https://api.moonshot.cn/v1',
    model: 'moonshot-v1-8k',
    models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://platform.moonshot.cn/console/api-keys',
    keyFormat: 'sk-…',
    keyTest: /^sk-/,
  },
  {
    id: 'zhipu',
    name: '智谱 GLM',
    group: '国内云',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    model: 'glm-4-flash',
    models: ['glm-4-flash', 'glm-4-plus', 'glm-4-air'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    keyFormat: 'id.secret（中间一个点）',
    keyTest: /\S+\.\S+/,
    plans: [
      { name: '标准计费', baseUrl: 'https://open.bigmodel.cn/api/paas/v4' },
      // GLM Coding Plan 订阅用户走独立接入点
      { name: 'Coding Plan', baseUrl: 'https://open.bigmodel.cn/api/coding/paas/v4' },
    ],
  },
  {
    id: 'doubao',
    name: '豆包 / 火山方舟',
    group: '国内云',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    model: '',
    models: ['doubao-seed-2-1-pro', 'doubao-seed-2-1-turbo'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://console.volcengine.com/ark',
    keyFormat: '火山方舟 API Key（无 sk- 前缀）',
    note: '模型名填控制台「推理接入点」的 ID（ep- 开头），也可直接填模型 ID。',
  },
  {
    id: 'hunyuan',
    name: '腾讯混元',
    group: '国内云',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    model: 'hunyuan-turbo',
    models: ['hunyuan-turbo', 'hunyuan-pro', 'hunyuan-lite'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://console.cloud.tencent.com/hunyuan/api-key',
    note: '混元正逐步迁移到 TokenHub，若此地址失效请以控制台最新地址为准。',
  },
  {
    id: 'qianfan',
    name: '百度千帆（文心）',
    group: '国内云',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    model: 'ernie-4.0-turbo-8k',
    models: ['ernie-4.0-turbo-8k', 'ernie-3.5-8k', 'ernie-speed-8k'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://console.bce.baidu.com/qianfan/ais/console/apiKey',
    keyFormat: 'bce-v3/…（v2 鉴权）',
    note: 'Key 以 bce-v3/ 开头，是「应用 API Key」而非 AK/SK。',
  },
  {
    id: 'qianfan-anthropic',
    name: '百度千帆（Anthropic 协议）',
    group: '国内云',
    baseUrl: 'https://qianfan.baidubce.com/anthropic',
    model: '',
    protocol: 'anthropic',
    needKey: true,
    keyUrl: 'https://console.bce.baidu.com/qianfan/ais/console/apiKey',
    keyFormat: 'bce-v3/…（v2 鉴权）',
    note: '走 /v1/messages 协议，用来在千帆上调 Claude 系模型；模型名以千帆模型列表为准。',
  },
  {
    id: 'spark',
    name: '讯飞星火',
    group: '国内云',
    baseUrl: 'https://spark-api-open.xf-yun.com/v1',
    model: 'generalv3.5',
    models: ['generalv3.5', '4.0Ultra', 'lite'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://console.xfyun.cn/services/bmx',
    keyFormat: 'APIKey:APISecret（英文冒号拼接）',
    keyTest: /:.+/,
    note: 'Key 填控制台的 APIKey:APISecret（中间用英文冒号拼接）。',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    group: '国内云',
    baseUrl: 'https://api.minimaxi.com/v1',
    model: 'MiniMax-Text-01',
    models: ['MiniMax-Text-01', 'MiniMax-M1'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    keyFormat: 'JWT 令牌（ey 开头的长串）',
    keyTest: /^ey/,
  },
  {
    id: 'minimax-anthropic',
    name: 'MiniMax（Anthropic 协议）',
    group: '国内云',
    baseUrl: 'https://api.minimaxi.com/anthropic',
    model: '',
    protocol: 'anthropic',
    needKey: true,
    keyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    note: '走 /v1/messages 协议，可用 Claude 系模型名。',
  },
  {
    id: 'stepfun',
    name: '阶跃星辰',
    group: '国内云',
    baseUrl: 'https://api.stepfun.com/v1',
    model: '',
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://platform.stepfun.com/interface-key',
    keyFormat: 'sk-…',
    keyTest: /^sk-/,
  },
  {
    id: 'lingyi',
    name: '零一万物',
    group: '国内云',
    baseUrl: 'https://api.lingyiwanwu.com/v1',
    model: 'yi-lightning',
    models: ['yi-lightning', 'yi-large'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://platform.lingyiwanwu.com/apikeys',
  },
  {
    id: 'baichuan',
    name: '百川智能',
    group: '国内云',
    baseUrl: 'https://api.baichuan-ai.com/v1',
    model: 'Baichuan4',
    models: ['Baichuan4', 'Baichuan3-Turbo'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://platform.baichuan-ai.com/console/apikey',
  },
  {
    id: 'siliconflow',
    name: '硅基流动 SiliconFlow',
    group: '国内云',
    baseUrl: 'https://api.siliconflow.cn/v1',
    model: 'Qwen/Qwen2.5-7B-Instruct',
    models: ['Qwen/Qwen2.5-7B-Instruct', 'deepseek-ai/DeepSeek-V3', 'THUDM/glm-4-9b-chat'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://cloud.siliconflow.cn/account/ak',
    keyFormat: 'sk-…',
    keyTest: /^sk-/,
  },
  {
    id: 'modelscope',
    name: '魔搭 ModelScope',
    group: '国内云',
    baseUrl: 'https://api-inference.modelscope.cn/v1',
    model: '',
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://modelscope.cn/my/myaccesstoken',
    keyFormat: 'ms-…',
    keyTest: /^ms-/,
    note: '魔搭社区的 OpenAI 兼容推理接口，模型名用社区模型 ID。',
  },
  {
    id: 'mimo',
    name: '小米 MiMo',
    group: '国内云',
    baseUrl: 'https://api.xiaomimimo.com/v1',
    model: 'mimo-v2.5',
    models: ['mimo-v2.5', 'mimo-v2.5-pro'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://platform.xiaomimimo.com/console/api-keys',
    keyFormat: 'sk-…',
    keyTest: /^sk-/,
    plans: [
      { name: '按量付费', baseUrl: 'https://api.xiaomimimo.com/v1', keyFormat: 'sk-…', keyTest: /^sk-/ },
      { name: 'Token Plan · 中国', baseUrl: 'https://token-plan-cn.xiaomimimo.com/v1', keyFormat: 'tp-…', keyTest: /^tp-/ },
      { name: 'Token Plan · 新加坡', baseUrl: 'https://token-plan-sgp.xiaomimimo.com/v1', keyFormat: 'tp-…', keyTest: /^tp-/ },
      { name: 'Token Plan · 欧洲', baseUrl: 'https://token-plan-ams.xiaomimimo.com/v1', keyFormat: 'tp-…', keyTest: /^tp-/ },
    ],
    note: 'Token Plan 订阅用户：在「接口地址」下方切换到对应接入点，Key 是 tp- 开头（订阅页专属），别填成按量付费的 sk- Key。',
  },

  // ---------- 海外 ----------
  {
    id: 'openai',
    name: 'OpenAI',
    group: '海外',
    baseUrl: 'https://api.openai.com/v1',
    model: 'gpt-4o-mini',
    models: ['gpt-4o-mini', 'gpt-4o', 'gpt-4.1-mini'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://platform.openai.com/api-keys',
    keyFormat: 'sk-…',
    keyTest: /^sk-/,
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    group: '海外',
    baseUrl: 'https://api.anthropic.com/v1',
    model: '',
    protocol: 'anthropic',
    needKey: true,
    keyUrl: 'https://console.anthropic.com/settings/keys',
    keyFormat: 'sk-ant-…',
    keyTest: /^sk-ant-/,
    note: 'Anthropic 原生协议（/v1/messages），模型名点「获取模型列表」选择。',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    group: '海外',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    model: 'gemini-2.5-flash',
    models: ['gemini-2.5-flash', 'gemini-2.5-pro', 'gemini-2.5-flash-lite'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://aistudio.google.com/apikey',
    keyFormat: 'AIza…（39 位）',
    keyTest: /^AIza/,
    note: 'Google 官方 OpenAI 兼容层，直接用 AI Studio 的 Key。',
  },
  {
    id: 'xai',
    name: 'xAI Grok',
    group: '海外',
    baseUrl: 'https://api.x.ai/v1',
    model: '',
    models: ['grok-4', 'grok-3'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://console.x.ai',
    keyFormat: 'xai-…',
    keyTest: /^xai-/,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    group: '海外',
    baseUrl: 'https://api.mistral.ai/v1',
    model: 'mistral-small-latest',
    models: ['mistral-small-latest', 'mistral-medium-latest', 'mistral-large-latest'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://console.mistral.ai/api-keys',
  },
  {
    id: 'groq',
    name: 'Groq',
    group: '海外',
    baseUrl: 'https://api.groq.com/openai/v1',
    model: 'llama-3.3-70b-versatile',
    models: ['llama-3.3-70b-versatile', 'openai/gpt-oss-120b'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://console.groq.com/keys',
    keyFormat: 'gsk_…',
    keyTest: /^gsk_/,
  },
  {
    id: 'together',
    name: 'Together AI',
    group: '海外',
    baseUrl: 'https://api.together.xyz/v1',
    model: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://api.together.ai/settings/api-keys',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    group: '海外',
    baseUrl: 'https://api.perplexity.ai',
    model: 'sonar',
    models: ['sonar', 'sonar-pro'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://www.perplexity.ai/settings/api',
    keyFormat: 'pplx-…',
    keyTest: /^pplx-/,
  },

  // ---------- 聚合 / 中转 ----------
  {
    id: 'openrouter',
    name: 'OpenRouter',
    group: '聚合/中转',
    baseUrl: 'https://openrouter.ai/api/v1',
    model: '',
    models: ['openai/gpt-4o-mini', 'anthropic/claude-sonnet-4.5', 'deepseek/deepseek-chat', 'google/gemini-2.5-flash'],
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://openrouter.ai/keys',
    keyFormat: 'sk-or-…',
    keyTest: /^sk-or-/,
    note: '一个 Key 打通上百个模型；模型名必须带厂商前缀，如 deepseek/deepseek-chat。',
  },
  {
    id: 'ai302',
    name: '302.AI（中转）',
    group: '聚合/中转',
    baseUrl: 'https://api.302.ai/v1',
    model: '',
    protocol: 'openai',
    needKey: true,
    keyUrl: 'https://302.ai',
    keyFormat: 'sk-…',
    keyTest: /^sk-/,
    note: '中转站，模型名按其模型列表填写。',
  },
  {
    id: 'custom',
    name: '自定义（OpenAI 兼容）',
    group: '聚合/中转',
    baseUrl: '',
    model: '',
    protocol: 'openai',
    needKey: true,
    keyFormat: '按服务商要求填写',
    note: '任意 OpenAI 兼容服务：填接口地址 + 模型名，需要鉴权就填 Key。',
  },
  {
    id: 'custom-anthropic',
    name: '自定义（Anthropic 协议）',
    group: '聚合/中转',
    baseUrl: '',
    model: '',
    protocol: 'anthropic',
    needKey: true,
    note: '走 /v1/messages 的中转或自建服务（如 one-api、new-api 的 Anthropic 通道）。',
  },

  // ---------- 本地 ----------
  {
    id: 'ollama',
    name: 'Ollama（本地）',
    group: '本地',
    baseUrl: 'http://127.0.0.1:11434/v1',
    model: '',
    protocol: 'ollama',
    needKey: false,
    note: '先执行 ollama serve（或打开 Ollama 桌面端），ollama pull 模型名 下载后点「获取模型列表」。',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio（本地）',
    group: '本地',
    baseUrl: 'http://127.0.0.1:1234/v1',
    model: '',
    protocol: 'openai',
    needKey: false,
    note: '需在 LM Studio 的 Local Server / Developer 页启动本地服务。',
  },
  {
    id: 'vllm',
    name: 'vLLM（本地）',
    group: '本地',
    baseUrl: 'http://127.0.0.1:8000/v1',
    model: '',
    protocol: 'openai',
    needKey: false,
    note: '启动时若加了 --api-key，就在 Key 框填同一个值。',
  },
  {
    id: 'xinference',
    name: 'Xinference（本地）',
    group: '本地',
    baseUrl: 'http://127.0.0.1:9997/v1',
    model: '',
    protocol: 'openai',
    needKey: false,
  },
  {
    id: 'localai',
    name: 'LocalAI（本地）',
    group: '本地',
    baseUrl: 'http://127.0.0.1:8080/v1',
    model: '',
    protocol: 'openai',
    needKey: false,
  },
  {
    id: 'jan',
    name: 'Jan / llama.cpp（本地）',
    group: '本地',
    baseUrl: 'http://127.0.0.1:1337/v1',
    model: '',
    protocol: 'openai',
    needKey: false,
  },
];

export const PROVIDER_GROUPS: ProviderPreset['group'][] = ['国内云', '海外', '聚合/中转', '本地'];

// 设置页顶部的一排快捷入口
export const QUICK_IDS = ['deepseek', 'qwen', 'kimi', 'zhipu', 'doubao', 'mimo', 'openai', 'anthropic', 'ollama'];

export function findPreset(id: string): ProviderPreset | undefined {
  return PROVIDERS.find((p) => p.id === id);
}

// 兼容旧配置：老配置里 provider 可能不在预设中，按协议/地址猜一个
export function presetOf(providerId?: string, protocol?: string, baseUrl?: string): ProviderPreset | undefined {
  const byId = findPreset(providerId ?? '');
  if (byId) return byId;
  if (protocol === 'anthropic') return findPreset('custom-anthropic');
  if (baseUrl?.includes('anthropic')) return findPreset('custom-anthropic');
  if (baseUrl?.includes(':11434')) return findPreset('ollama');
  return findPreset('custom');
}
